name: Build Helm Chart
on:
  push:
    branches:
      - main
      - helm-chart
    paths:
      - chart/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: auth
      name: Auth to GCloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCLOUD_AUTH }}'